# Generated by Django 4.1.4 on 2023-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='protrainyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_branch', models.CharField(max_length=5)),
                ('user_password', models.CharField(max_length=10)),
            ],
        ),
    ]
